### ISSUE TITLE
Closes

### ISSUE THREAD

**Issue by aziggya** [ProjectSynchro/WalrusRPG#1]
I open this using Technic Pack using the latest version, and it opens to the Mojang loading screen however, it closes and returns to TechnicPack after around 30 seconds.

**To Reproduce**
1. Download WalrusRPG on technicpack using the latest version
2. Click on 'play'
3. Minecraft opens to the Mojang loading screen

**Expected behavior**
Its meant to load up the starting screen of minecraft

**Comment by ProjectSynchro** [comment]
Could you attach the crash log that would be in the crash-reports folder in your modpack folder?
I can't really tell much from what you've told me so far.

**Comment by ProjectSynchro** [comment]
Duplicate of #2
